In [16]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"



<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [2]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [5]:
a.shape

(3,)

In [6]:
print(a.shape[0])

3


In [8]:
for i in range(a.shape[0]):
    print(i)

0
1
2


In [9]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [14]:
def vectorAdd(a, b):
    v = np.array([0,0,0])
    for i in range(a.shape[0]):
        v[i] = a[i] + b[i]
    return v    
        

In [15]:
print(vectorAdd(v1, v2))

[5 7 9]
